### ISSUE TITLE
请问该版本和tensorflow serving性能对比是怎么样的？

### ISSUE THREAD

**Issue by drfilter** [tobegit3hub/simple_tensorflow_serving#10]
请问该版本和tensorflow serving性能对比是怎么样的？
大约会慢多少？

**Comment by tobegit3hub** [comment]
We have some benchmark scripts in <https://github.com/tobegit3hub/simple_tensorflow_serving/tree/master/benchmark> . `Simple TensorFlow Serving` uses HTTP protobuf and be implemented in Python which expects not as fast as `TensorFlow Serving` in C++.

But it depends on how you test and what model you are using. And if you use Java client for `TensorFlow Serving`, it is much slower for the first request because of the bug of Java gRPC client.

**Comment by tobegit3hub** [comment]
We have benchmarked and provide the result in https://github.com/tobegit3hub/simple_tensorflow_serving#performance .

Hope it helps 😃
